config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  get 'top/login'
  post 'top/login'
  get 'top/logout'
  resources :users, only: [:index, :new, :create, :destroy]
  resources :tweets, only: [:index, :new, :create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :message, presence: true, length: {maximum: 140}

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  
  def like(user)
    likes.create(user_id: user.id)
  end
  
  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
  
  def liked?(user)
    like_users.include?(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :uid, presence: true, uniqueness: true
  validates :pass, presence: true, length: {minimum: 4}
  validates :password, presence: true, confirmation: true
  
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_tweets, through: :likes, source: :tweet

  attr_accessor :password, :password_confirmation
  
  def password=(val)
    if val.present?
      self.pass = BCrypt::Password.create(val)
    end
    @password = val
  end
  
  def self.authenticate(uid, pass)
    user = User.find_by(uid: uid)
    if user and BCrypt::Password.new(user.pass) == pass
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_user
        if session[:login_uid]
            User.find_by(uid: session[:login_uid])
        end
    end
    helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    unless tweet.liked?(current_user)
      tweet.like(current_user)
    end
    redirect_to root_path
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.liked?(current_user)
      tweet.unlike(current_user)
    end
    redirect_to root_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def login
    user = User.authenticate(params[:uid], params[:pass])
    if user
      session[:login_uid] = params[:uid]
      redirect_to root_path
    else
      render top_login_path
    end
  end

  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end

  def new
    @tweet = Tweet.new
  end

  def create
    user_id = User.find_by(uid: session[:login_uid]).id
    @tweet = Tweet.new(message: params[:tweet][:message], user_id: user_id)
    if @tweet.save
      redirect_to tweets_path
    else
      render new_tweet_path
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to tweets_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(
      uid: params[:user][:uid],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation])
    if @user.save
      flash[:info] = 'ユーザを登録完了しました。'
      redirect_to users_path
    else
      render new_user_path
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/login.html.erb
<% if flash[:info] %>
  <%= flash[:info] %>
<% end %>

<%= form_tag top_login_path, method: :post  do  %>
    <%= label_tag :uid, 'ユーザID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>

<p><%= link_to '戻る', :back %>

app/views/tweets/index.html.erb
<% if flash[:info] %>
<%= flash[:info] %>
<% end %>

<% if @tweet.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @tweet.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<% if current_user %>
  <%= form_for @tweet, url: {action: :create} do |f| %>
  <p>
    <%= f.text_field :message %>
    <%= f.submit "ツイート" %>
  </p>
  <% end %>
<% end %>


<% @tweets.each do |t| %>
<p>
  <%= t.message %>
  <%= User.find(t.user_id).uid %>
  <% if current_user and t.user_id == current_user.id %>
    <%= link_to '削除', tweet_path(t), method: :delete, data: { confirm: '削除していいですか？' }  %>
  <% end %>
  <% if current_user %>
    <% if Like.find_by(user_id: current_user.id, tweet_id: t.id) %>
      <%= link_to '❤️', like_path(t), method: :delete %>
    <% else %>
      <%= link_to '♡', likes_path(tweet_id: t.id), method: :post %>
    <% end %>
  <% end %>
</p>
<% end %>

<% if current_user %>
  <p><%= link_to 'ログアウト', top_logout_path %></p>
<% else %>
  <p><%= link_to 'ログイン', top_login_path %></p>
<% end %>

<p><%= link_to 'ユーザID一覧', users_path %></p>
<p><%= link_to 'ユーザ登録', new_user_path %></p>

app/views/users/index.html.erb
<% if flash[:info] %>
  <%= flash[:info] %>
<% end %>

<% @users.each do |e| %>
<p>
  <%= e.uid %>
  <%= e.pass %>
  <%= link_to '削除', user_path(e), method: :delete %>
</p>
<% end %>

<p><%= link_to 'ユーザ登録', new_user_path %></p>

<p><%= link_to '戻る', '/' %></p>

app/views/users/new.html.erb
<% if @user.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user, url: {action: :create} do |f| %>
<p>
  <%= f.label :uid, 'ユーザID' %>
  <%= f.text_field :uid %>
</p>
<p>
  <%= f.label :pass, 'パスワード' %>
  <%= f.password_field :password %>
</p>
<p>
  <%= f.label :password_confirmation,'パスワード（確認）' %>
  <%= f.password_field :password_confirmation %>
</p>
<p>
  <%= f.submit '登録' %>
</p>
<% end %>

<p><%= link_to '戻る', :back %>